language: java
jdk:
  - openjdk8
branches:
  only:
    - master
before_install:
  - chmod +x gradlew

# travis ci server's home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시하여, 같은 의존성은 다음 배포 때 받지 않도록
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# push 되었을때 clean, build를 수행
script: "./gradlew clean build"

# codedeploy는 jar 인식 못하므로 압축
before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy #
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

# 외부 서비스와 연동될 행위 선언, 업로드 배포 등
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myfl-springboot2-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근
    local_dir: deploy #
    wait-until-deployed: true

# 완료시 noti
notifications:
  email:
    recipients:
      slche25@gmail.com