#codedeploy version
version: 0.0
os: linux
files:
  # 이동 대상 전체
  - source: /
    # 받을 위치
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

# CodeDeploy가 넘겨준 모든 파일들의 권한을 ec2-user로
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# 배포단계에서 실행할 명령어 지정
hooks:
  AfterInstall:
    - location: stop.sh # nginx와 연결되지 않은 부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # nginx와 연결되지 않은 포트로 부트 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 부트가 정상 실행되는지 확인
      timeout: 60
      runas: ec2-user